### ISSUE TITLE
UTF-8 txt returns null

### ISSUE THREAD

**Issue by fnils** [hryz/MimeDetective.InMemory#2]
I have tried with different encoding but it doesn't seem make a difference.
byte[] file.DetectMimeType() returns null.

**Comment by badreddine-dlaila** [comment]
Any news about this Issue ? Can give a hand if needed 😉

**Comment by hryz** [comment]
Sorry for a super late reply.
Regular UTF-8 files can't be detected. In UTF-8 encoding each character can be from 1 to 4 bytes. In the case of Latin characters, the bytes will be exactly the same as in ASCII. The only way to tell that this is Unicode text is BOM https://en.wikipedia.org/wiki/Byte_order_mark therefore only UTF8+BOM are supported.
