### ISSUE TITLE
Mime Detective Update

### ISSUE THREAD

**Issue by TonyValenti** [hryz/MimeDetective.InMemory#4]
Hi @hryz -
My name is Tony Valenti and I am the new maintainer of Mime-Detective.  I have just published a major update that incorporates concepts from your fork as well as numerous other enhancements.

Would you take a look at the following:
https://github.com/MediatedCommunications/Mime-Detective
https://www.nuget.org/packages/Mime-Detective/

and let me know if there are any other optimizations/enhancements you think I should include?

(By the way, this is a total rewrite and every API signature is different.  Please make sure to look at the [readme](https://github.com/MediatedCommunications/Mime-Detective/blob/main/README.md)).

**Comment by hryz** [comment]
Thanks for sharing this information! It's nice to hear that the original lib has a new life. I'll take a look at it on the weekend.

**Comment by TonyValenti** [comment]
Hi @hryz - Wow!  It has been nearly a year!
Would you be willing to unlist the nuget package or transfer it over to me?

**Comment by hryz** [comment]
I stopped working on my open source projects when I left dotnet.
I'll unlist my packages on the weekend.
Sorry for inconvenience.

**Comment by TonyValenti** [comment]
No problem!  Thanks so much!

**Comment by hryz** [comment]
done! I've unlisted and marked as deprecated with a link to the original package
